#!/bin/bash

# check user has root permissions, required for some of the tests
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# install bats if it isnt installed
if ! dpkg -s bats 1>/dev/null 2>/dev/null
then
  # install bats
  apt install -y bats
fi


script_path="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
current_path=$(pwd)

cd $script_path

# run validation scripts
bats $script_path/validation-scripts

cd $current_path
